import { ScreenProvider } from './contexts/screenContexts'
import Navbar from '@/components/Navbar/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import { AuthProvider } from './contexts/authContexts'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <ScreenProvider>
    <html lang="en">
   
     
      <AuthProvider>
      <body className={inter.className}>
        <Navbar />
        {children}
        {/* <Footer/> */}
        </body>
        </AuthProvider>
        
    </html>
    </ScreenProvider>
  )
}
